
mandelbrot:
  width: 512
  height: 512
  x_min: -2.0
  x_max: 1.0
  y_min: -1.5
  y_max: 1.5
  max_iterations: 100
  background_color: 'black' # `red` or `green` or `blue` or `other`
  incremental_step: 50
  output: mandelbrot.png
